config/routes.rb
Rails.application.routes.draw do
  resources :wikis
  post 'wikis/downgrade'
  resources :charges, only: [:new, :create]

  resources :wikis, only: [] do
    resources :collaborators, only: [:create, :destroy]
  end

  devise_for :users

  #root 'welcome#index'
  root 'wikis#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :wiki

  include ActiveModel::Validations

  validates_with EmailValidator
  validates :email, uniqueness: true
end

app/models/concerns/email_validator.rb
class EmailValidator < ActiveModel::Validator
  def validate(collaborator)
    unless User.exists?('email' => collaborator[:email])
      collaborator.errors[:email] << 'Need an email that exists please.'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :wikis, dependent: :destroy

  before_save { self.role ||= :standard }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user

  has_many :collaborators

  default_scope { order('created_at DESC') }

  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
require 'cost_amount'

class ChargesController < ApplicationController
  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card:  params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer:    customer.id,
      amount:      Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency:    'usd'
    )

    flash[:notice] = "You are now a premium user, #{current_user.email}, congratulations!"
    current_user.premium!
    redirect_to wikis_url

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path

  end

  def new
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: Amount.default
    }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
    @wiki = Wiki.find(params[:wiki_id])
    collaborator = @wiki.collaborators.new(collaborator_params)

    if collaborator.save
      flash[:notice] = "Collaborator saved successfully."
      redirect_to @wiki
    else
      flash[:alert] = "Collaborator failed to save."
      redirect_to @wiki
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    collaborator = @wiki.collaborators.find(params[:id])

    if collaborator.destroy
      flash[:notice] = "Collaborator was removed."
      redirect_to @wiki
    else
      flash[alert] = "Collaborator couldn't be removed successfully. Try again."
      redirect_to @wiki
    end
  end

  private
  def collaborator_params
    params.require(:collaborator).permit(:email)
  end

  def change_this_name(collaborator)
    (User.all.each { |u| u.email == collaborator.email }.any?)# && !(@wiki.collaborators.each { |c| c.email == collaborator.email }.any?)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authorize_standard, except: [:index, :show, :downgrade, :new, :edit, :create, :update, :destroy]
  before_action :authorize_premium, except: [:index, :show, :edit, :new, :create, :edit, :update, :downgrade]

  def index
    #@wikis = Wiki.all
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    wiki_params
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    wiki_params
    @wiki.collaborators = params[:wiki][:email]
    #authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  def downgrade
    current_user.wikis.each do |wiki|
      wiki.update_attribute(:private, false)
    end
    current_user.standard!
    flash[:notice] = "You are now a standard user, #{current_user.email}, come back!"
    redirect_to wikis_url
  end

  private
  def wiki_params
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
  end

  def authorize_standard
    if current_user.standard?
      flash[:alert] = "You must be an admin or premium user to do that."
      redirect_to wikis_path
    end
  end

  def authorize_premium
    wiki = Wiki.find(params[:id])

    unless current_user == wiki.user || current_user.admin?
      flash[:alert] = "You must be an admin or the author to do that."
      redirect_to [wiki]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink: true,
      superscript: true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
  def self.change_this_name(collaborator)
    (User.all.each { |u| u.email == collaborator.email }.any?) && !(@wiki.collaborators.each { |c| c.email == collaborator.email }.any?)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_for_wiki?(wiki)
    current_user && (current_user == wiki.user || current_user.admin?)
  end

  def user_is_authorized_for_private_wiki?(wiki)
    current_user.admin? || !wiki.private || current_user == wiki.user || wiki.collaborators.exists?('email' => current_user.email)
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/_collaborator.html.erb
<% if user_is_authorized_for_private_wiki?(@wiki) %>
  <div class="media">
    <div class="media-body">
      <small>
        <%= collaborator.email %>
        <% if current_user == @wiki.user %>
          | <%= link_to "Remove Callaborator", [@wiki, collaborator], method: :delete %>
        <% end %>
      </small>
  </div>
<% end %>

app/views/collaborators/_form.html.erb
<% if current_user == @wiki.user %>
  <h4>Add a collaborator</h4>
  <%= form_for [wiki, collaborator] do |f| %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control', placeholder: "Enter a collaborator" %>
    </div>
    <%= f.submit "Submit collaborator", class: 'btn btn-default pull-right' %>
  <% end %>
<% end %>

app/views/collaborators/new.html.erb
<h1>New Collaborator</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @collaborator do |f| %>
      <div class="form-group">
        <%= f.label 'Collaborators' %>
        <%= f.text_field :email, class: 'form-control', placeholder: "Enter collaborator email" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <% if current_user.standard? %>
            <li><%= link_to "Upgrade", new_charge_url %></li>
          <% else %>
            <li><%= link_to "Downgrade", wikis_downgrade_path, method: :post, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade to a standard account?'} %></li>
          <% end %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make sure it makes sense.</li>
      <li>Don't talk as a sailor.</li>
      <li>Markdown is available for body text</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholders: "Enter wiki body" %>
      </div>
      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>
  Wikis
  <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
</h1>

<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <% if wiki.private == true %>
              <b><%= link_to wiki.title, wiki, { :style=>"color: darkred" } %></b>
            <% else %>
              <%= link_to wiki.title, wiki %>
            <% end %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make sure it makes sense.</li>
      <li>Don't talk as a sailor</li>
      <li>Markdown is available for body text</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1>
  <%= @wiki.title %> <br>
  <small>
    <h5>
      submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.email %>
    </h5>
  </small>
</h1>

<div class="row">
  <div class="col-md-8">
    <% if user_is_authorized_for_private_wiki?(@wiki) %>
      <p><h4><%= markdown(@wiki.body) %></h4></p>
    <% else %>
      <p><i>This post was made private by <b><%= @wiki.user.email %></b>.</i></p>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% if user_is_authorized_for_wiki?(@wiki) %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    <% end %>
  </div>
  <% if @wiki.private %>
    <div class="col-md-8">
      <h3>Collaborators</h3>
      <%= render @wiki.collaborators %>
      </br>
      <% if current_user %>
        <%= render 'collaborators/form', collaborator: Collaborator.new, wiki: @wiki %>
      <% end %>
    </div>
  <% end %>
</div>